version: "3"
services:
  zoo-1:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zoo-1
    environment:
      ZOOKEEPER_SERVER_ID: "1"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: "zoo-1:2888:3888;zoo-2:2888:3888;zoo-3:2888:3888"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
  zoo-2:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zoo-2
    environment:
      ZOOKEEPER_SERVER_ID: "2"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: "zoo-1:2888:3888;zoo-2:2888:3888;zoo-3:2888:3888"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"


  zoo-3:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zoo-3
    environment:
      ZOOKEEPER_SERVER_ID: "3"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: "zoo-1:2888:3888;zoo-2:2888:3888;zoo-3:2888:3888"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"

  kafka-1:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka-1
    depends_on:
      - zoo-1
      - zoo-2
      - zoo-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo-1:2181,zoo-2:2181,zoo-3:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-1:9092"
      KAFKA_BROKER_ID: "1"
      KAFKA_HEAP_OPTS: "-Xmx1024M -Xms512M"
  kafka-2:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka-2
    depends_on:
      - zoo-1
      - zoo-2
      - zoo-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo-1:2181,zoo-2:2181,zoo-3:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-2:9092"
      KAFKA_BROKER_ID: "2"
      KAFKA_HEAP_OPTS: "-Xmx1024M -Xms512M"
  kafka-3:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka-3
    depends_on:
      - zoo-1
      - zoo-2
      - zoo-3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo-1:2181,zoo-2:2181,zoo-3:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-3:9092"
      KAFKA_BROKER_ID: "3"
      KAFKA_HEAP_OPTS: "-Xmx1024M -Xms512M"


  magic-balance:
    build: .
    environment:
      JAVA_OPTS: "-Xmx1024M -Xms512M"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8090:8080"


